interface StringHash {
  [key: string]: string;
}

export const settingsCarsStrings = {
  id: '№',
  date: 'Дата',
  ownerNumber: 'Телефон',
  status: 'Статус',
  brandAndModel: 'Автомобиль',
  engine: 'Мотор',
  engineCapacity: 'Объём мотора',
  mileage: 'Пробег',
  year: 'Год выпуска',
  mark: 'Марка',
  model: 'Модель',
  transmission: 'Коробка передач',
  color: 'Цвет',
  driveType: 'Привод',
  linkToAd: 'Ссылка на объявление',
  carOwnerPrice: 'Цена клиента',
  trueCarPrice: 'Цена на руки',
  commission: 'Комиссия',
  comment: 'Комментарии',
  dateOfLastStatusChange: 'Дата последнего изменения статуса',
  worksheet: 'Анкета',
  bargain: 'Торг',
  adPrice: 'Цена на сайте',
  shootingDate: 'Дата съёмки',
  shootingTime: 'Время съёмки',
  ourLinks: 'Наши объявления',
  ownerName: 'Имя',
  contactCenterSpecialistId: 'Специалист контактного центра',
  carShootingSpecialistId: 'Специалист отдела съёмок',
  source: 'Источник',
  photos: 'Фото',
  photo360: 'Фото 360',
  linkToVideo: 'Ссылка на видео',
  bodyType: 'Тип кузова',

  // nextAction: 'Следующее действие',
};
