interface StringHash {
  [key: string]: string;
}

export const settingsClientsStrings: StringHash = {
  id: '№',
  date: 'Дата создания',
  source: 'Источник',
  name: 'Имя',
  number: 'Номер телефона',
  email: 'Электронная почта',
  carIds: 'Автомобили',
  'payment-type': 'Вид оплаты',
  'trade-in-auto': 'Авто в зачет',
  'deal-status': 'Статус сделки',
  comment: 'Коммент',
  description: 'Описание',
  'next-action': 'Следующее действие',
  'date-next-action': 'Дата следующего действия',
  'client-status': 'Статус клиента',
  "specialist-id": 'Специалист',
}

export const generalSettingsStrings: StringHash = {
  id: '№',
  date: 'Дата создания',
  source: 'Источник',
  name: 'Имя',
  number: 'Номер телефона',
  email: 'Электронная почта',
  carIds: 'Автомобили',
  'payment-type': 'Вид оплаты',
  'trade-in-auto': 'Авто в зачет',
  'deal-status': 'Статус сделки',
  // comment: 'Коммент',
  description: 'Описание',
  'next-action': 'Следующее действие',
  'date-next-action': 'Дата следующего действия',
  'client-status': 'Статус клиента',
  "specialist-id": 'Специалист',
  // date: 'Дата',
  ownerNumber: 'Телефон',
  status: 'Статус',
  brandAndModel: 'Автомобиль',
  engine: 'Мотор',
  engineCapacity: 'Объём',
  mileage: 'Пробег',
  year: 'Год',
  mark: 'Марка',
  model: 'Модель',
  transmission: 'Коробка',
  color: 'Цвет',
  driveType: 'Привод',
  linkToAd: 'Ссылка',
  carOwnerPrice: 'Цена',
  trueCarPrice: 'Цена на руки',
  commission: 'Комиссия',
  comment: 'Комментарий',
  dateOfLastStatusChange: 'Дата действия',
  dateOfNextAction: 'Дата действия',
  worksheet: 'Анкета',
  bargain: 'Торг',
  adPrice: 'Цена на сайте',
  shootingDate: 'Дата съёмки',
  shootingTime: 'Время съёмки',
  ourLinks: 'Опубликовано объявлений',
  ownerName: 'Имя',
  contactCenterSpecialistId: 'Специалист ОКЦ',
  carShootingSpecialistId: 'Специалист ОСА',
  // source: 'Источник',
  photos: 'Фото',
  photo360: 'Фото 360',
  linkToVideo: 'Видео',
  bodyType: 'Кузов',
  dateOfLastCustomerCall: 'Дата последнего звонка',
  'call-request-sources': 'источник звонка-заявки'
}